server: 
  port: 8081
  servlet: 
    context-path: /middleware-mb

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/Pagatutti
          jwk-set-uri: http://localhost:8080/auth/realms/Pagatutti/protocol/openid-connect/certs
